#!/usr/bin/env python3
"""Generate the public command reference from the production TOOL_CATALOG."""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path
import re


REPO = Path(__file__).resolve().parents[1]
RESOURCES = REPO / "src" / "glyphs-mcp" / "Glyphs MCP.glyphsPlugin" / "Contents" / "Resources"
OUTPUT = REPO / "content" / "reference" / "command-set.mdx"
README = REPO / "README.md"
sys.path.insert(0, str(RESOURCES))

from tool_catalog import TOOL_CATALOG, active_entries, app_only_entries, model_entries


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render() -> str:
    active = active_entries()
    removed = tuple(entry for entry in TOOL_CATALOG.values() if entry.state == "removed")
    counts = Counter(entry.category for entry in active)
    lines = [
        "---",
        "title: Command set",
        "description: Catalog-generated reference for every active Glyphs MCP tool.",
        "---",
        "",
        "<!-- Generated by scripts/generate_tool_catalog_docs.py. Do not edit this table by hand. -->",
        "",
        "Glyphs MCP 1.8 uses one catalog-driven surface: **{} active tools**, with **{} model-visible** and **{} app-only** tools. There is no Read-only/Edit profile selector; safety is expressed per tool through MCP annotations, explicit targets, dry runs, confirmation, verification, and rollback.".format(
            len(active), len(model_entries()), len(app_only_entries())
        ),
        "",
        "App-only tools support the embedded feedback interface or host UI and are hidden from model routing when the client honors MCP Apps visibility. Structured results are additive for candidate, curve, spacing, and kerning workflows; their text content remains compatible with 1.7 clients.",
        "",
        "## Category summary",
        "",
        "| Category | Active tools |",
        "| --- | ---: |",
    ]
    for category, count in sorted(counts.items()):
        lines.append("| `{}` | {} |".format(category, count))
    lines.extend(
        [
            "",
            "## Active tools",
            "",
            "| Tool | Title | Category | Visibility | Effect | Structured output | Description |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for entry in sorted(active, key=lambda item: (item.category, item.name)):
        lines.append(
            "| `{}` | {} | `{}` | `{}` | `{}` | {} | {} |".format(
                entry.name,
                _escape(entry.title),
                entry.category,
                entry.visibility,
                entry.effect,
                "`{}`".format(entry.output_schema) if entry.output_schema else "—",
                _escape(entry.description),
            )
        )
    lines.extend(
        [
            "",
            "## Removed in 1.8",
            "",
            "These tombstones are retained for migration guidance but are not registered.",
            "",
            "| Removed tool | Replacement |",
            "| --- | --- |",
        ]
    )
    for entry in sorted(removed, key=lambda item: item.name):
        lines.append("| `{}` | `{}` |".format(entry.name, entry.replacement))
    lines.extend(
        [
            "",
            "## Curve review in 1.8",
            "",
            "`review_curve_quality` defaults to adaptive geometry data version 2 and reports extrema, inflections, stationary points, cusps, arc length, turning angle, bounded self-intersections, and G0/G1/G2 join measurements. Use `analysis_mode=\"sampled_v1\"` only for a reproducible 1.7 sampling baseline.",
            "",
            "`review_curve_quality_across_masters` compares those measurements only after compatible topology and cubic mapping are verified. `set_curve_review_overlay` accepts `overlays=[\"curvature\"]`, `overlays=[\"curve_events\"]`, or both; candidate differences remain in the separate Candidate Reporter.",
            "",
            "## Candidate safety sequence",
            "",
            "Use a typed preview tool, inspect `get_outline_candidate_state`, call `review_outline_candidate_session`, dry-run `accept_outline_candidate_session` with the returned token, and request explicit approval before confirmed acceptance. Materialize only when manual editing is needed. None of these tools saves the font.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    OUTPUT.write_text(render(), encoding="utf-8")
    readme = README.read_text(encoding="utf-8")
    section = """## Command Set (MCP server v1.8.0)

Glyphs MCP exposes **{} active tools** through one catalog-driven surface:
**{} are model-visible** and **{} are app-only**. Every tool has a concise
title and description, four MCP safety hints, a category, visibility, effect
class, lifecycle state, and optional structured-output schema.

The generated [command reference](https://thierryc.github.io/Glyphs-mcp/reference/command-set)
is the authoritative list. README intentionally does not duplicate the full
table. This catalog is shipped in this repo (version `1.8.0`). Typical
workflows begin with `list_open_fonts`, resolve explicit glyph
and master targets, review or preview a detached candidate, dry-run changes,
and ask for approval before confirmation. No edit tool saves implicitly.

Curve work normally uses `review_curve_quality`,
`review_curve_quality_across_masters`, `set_curve_review_overlay`, and the
candidate lifecycle. Use `execute_code` only when no dedicated typed tool fits.

""".format(len(active_entries()), len(model_entries()), len(app_only_entries()))
    pattern = re.compile(r"(?ms)^## Command Set \(MCP server v[^\n]+\)\n.*?(?=^## )")
    updated, count = pattern.subn(section, readme, count=1)
    if count != 1:
        raise RuntimeError("README Command Set section was not found exactly once")
    README.write_text(updated, encoding="utf-8")
    print("Generated {}".format(OUTPUT.relative_to(REPO)))
    print("Updated {} catalog summary".format(README.relative_to(REPO)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
