#!/usr/bin/env python3
"""Render or verify the catalog-derived Glyphs MCP v2 command reference."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
V2_SOURCE = REPO_ROOT / "src" / "glyphs-mcp-v2"
OUTPUT = REPO_ROOT / "content" / "reference" / "command-set-v2.mdx"
if str(V2_SOURCE) not in sys.path:
    sys.path.insert(0, str(V2_SOURCE))

from glyphs_mcp_v2.catalog import TOOL_DEFINITIONS  # noqa: E402


def render() -> str:
    lines = [
        "---",
        'title: "Glyphs MCP v2 command set"',
        'description: "Catalog-derived reference for the Glyphs MCP 2.0 model-visible tools."',
        "---",
        "",
        "<!-- Generated by scripts/render_v2_command_reference.py. -->",
        "",
        "This page lists the exact Glyphs MCP 2.0 callable surface. Input schemas",
        "and enum values are published by MCP discovery; this table records stable",
        "tool identity, effect, category, and intent.",
        "",
        "| Tool | Effect | Category | Purpose |",
        "| --- | --- | --- | --- |",
    ]
    for definition in TOOL_DEFINITIONS:
        description = definition.description.replace("|", "\\|").replace("\n", " ")
        lines.append(
            "| `{}` | `{}` | `{}` | {} |".format(
                definition.name,
                definition.effect,
                definition.category,
                description,
            )
        )
    lines.extend(
        [
            "",
            "## Surface invariants",
            "",
            "- The catalog contains exactly {} tools.".format(len(TOOL_DEFINITIONS)),
            "- Knowledge supplies cited evidence, skills supply font-design and",
            "  Glyphs expertise, and tools supply generic mechanics.",
            "- Every document mutation is previewed against exact identities and a",
            "  source fingerprint. `apply_change` consumes the stored patch without",
            "  rerunning planning or staged Python.",
            "- `execute_python` is a permanent fallback with `read_only`,",
            "  `staged_document`, and `live_open_world` modes.",
            "- Knowledge is pinned and searched offline; updates occur only through",
            "  reviewed deterministic builds.",
            "- Saving, export publication, UI actions, runtime repair, and open-world",
            "  Python remain explicit effect boundaries.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--stdout", action="store_true")
    arguments = parser.parse_args()
    rendered = render()
    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                "The v2 command reference is stale; run "
                "scripts/render_v2_command_reference.py.",
                file=sys.stderr,
            )
            return 1
        print("Verified catalog-derived Glyphs MCP v2 command reference.")
        return 0
    if arguments.stdout:
        sys.stdout.write(rendered)
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print("Rendered {}.".format(OUTPUT.relative_to(REPO_ROOT)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
